Fix nested routes
tourhero/travel-reopening pull request #266
Opened 2020-08-15 08:08 UTC by DctrG

- Allow for nested routes
- Move 404 route to bottom (wildcard route should be last)

2020-08-19 03:05 UTC, yurikoval requested changes

2020-08-19 03:05 UTC, yurikoval commented on src/router/index.ts
> +    children: [
This causes the root for oembed to redirect to 404.
Also, country-specific pages are rendered using the Default layout when it should be OembedLayout.

2020-08-19 03:50 UTC, mirhamasala commented on src/router/index.ts
> +    children: [
1. Actually, it seems 404 is coming from my commit `if (!country) { this.$router.push({ name: 'NotFound' }); return; }`

2. I fixed the rendering of the OembedLayout by adding the `name` and it's working

```
children: [
      { path: ':country.html', name: 'OembedMap', component: OembedMap },
    ],
```

2020-08-19 03:56 UTC, mirhamasala commented on public/index.html
> +    <base href="/" />
Without this, the children routes show only a blank screen, and this is the error message in the console that shows up.

<img width="560" alt="Screenshot 2020-08-19 at 11 43 41 AM" src="https://user-images.githubusercontent.com/26620750/90589704-49e09d80-e211-11ea-9a2f-e71c63791af6.png">

It's fixed with these instructions: https://github.com/vuejs/vue-router/issues/619

Another option would be to modify the `vue.config.js` line 11 with:
`? '/en/ultimate-guide-covid19-travel-restrictions-reopening/' : '/';`

2020-08-20 06:20 UTC, yurikoval approved these changes

2020-08-20 06:39 UTC, mirhamasala commented
@DctrG, thank you for contributing. ☀️ Merging now! 🚀

2020-08-20 06:39 UTC, merged