Add clipboard iframe
tourhero/travel-reopening pull request #289
Opened 2020-08-21 03:24 UTC by mirhamasala

2020-08-21 05:09 UTC, yurikoval commented on src/components/TitleMapSelect.vue
> +      copyError: null,
Do we need this? `copyError` is inverse of  `copySuccess`.

2020-08-21 05:10 UTC, yurikoval commented on src/components/TitleMapSelect.vue
> +        iframeSrc = `${baseUrl}/oembedmap/${this.country.name.toLowerCase()}.html`;
iframe url is incorrect and let's use the router api to get the correct one.

2020-08-21 05:39 UTC, mirhamasala commented on src/components/TitleMapSelect.vue
> +      copyError: null,
Refactored it.

2020-08-21 06:12 UTC, mirhamasala commented on src/components/TitleMapSelect.vue
> +        iframeSrc = `${baseUrl}/oembedmap/${this.country.name.toLowerCase()}.html`;
Done. Let me know if this is what you had in mind.

2020-08-21 07:35 UTC, yurikoval commented on src/components/TitleMapSelect.vue
> +      const iframeSrc = this.$router.resolve({ name: this.country ? 'CountryOembedMap' : 'OembedMap' }).href;
iframes will be embedded in other websites, so the url needs to be absolute: `https://www.tourhero.com/en/ultimate-guide-covid19-travel-restrictions-reopening/oembed-map/singapore.html`

2020-08-24 03:27 UTC, mirhamasala commented on src/components/TitleMapSelect.vue
> +      const iframeSrc = this.$router.resolve({ name: this.country ? 'CountryOembedMap' : 'OembedMap' }).href;
@yurikoval Done

2020-08-25 01:21 UTC, yurikoval requested changes

2020-08-25 01:21 UTC, yurikoval commented on src/components/TitleMapSelect.vue
> +      return `<iframe src="https://www.tourhero.com${process.env.BASE_URL}${iframeUri.replace('/', '')}"></iframe>`;
Let's move `iframeUri.replace` out into the line above.

2020-08-25 01:21 UTC, yurikoval commented on vue.config.js
> +  ? '/en/ultimate-guide-covid19-travel-restrictions-reopening/' : '/';
This change is not necessary -- not related to clipboard.

2020-08-25 01:21 UTC, yurikoval commented on src/views/Country.vue
> +      return `https://www.tourhero.com${this.baseUrl}img/travel-reopening-cover.jpg`;
Is this related to clipboard?

2020-08-25 01:59 UTC, mirhamasala commented on src/views/Country.vue
> +      return `https://www.tourhero.com${this.baseUrl}img/travel-reopening-cover.jpg`;
It's not. I'll remove it.

2020-08-25 05:08 UTC, yurikoval approved these changes

2020-08-25 05:13 UTC, merged