Morocco Update test
tourhero/travel-reopening pull request #300
Opened 2020-08-24 05:08 UTC by gabriel-seow

2020-08-24 07:41 UTC, jannwong commented on public/data/travel/MA.yml
> +      - 'In Marrakech, authorities will deny entry into 12 neighborhoods in the city](https://www.moroccoworldnews.com/2020/08/316061/morocco-intensifies-lockdown-measures-in-casablanca-marrakech/) a
missing `[`

2020-08-24 07:44 UTC, jannwong commented on public/data/travel/MA.yml
> +  restaurants_capacity_text: Maximum of 50% capacity
if restaurants capacity exist, this means that restaurants are open so we need to put the `yes` for the restaurants_open key.

restaurants_open: yes

2020-08-24 07:45 UTC, jannwong commented on public/data/travel/ML.yml
> +curfew_time_text: 12 am to 5 am
From 12 am to 5 am

2020-08-24 07:46 UTC, jannwong requested changes
![](https://media0.giphy.com/media/RhPvGbWK78A0/giphy.gif)

2020-08-25 03:38 UTC, jannwong commented on public/data/travel/BH.yml
> +  - Travelers will undergo two tests for COVID-19, one on arrival and another ten days after; however, they will not be required to continue self-isolation if the first test [produces a negative resu
...after. However, they....

2020-08-25 03:43 UTC, jannwong commented on public/data/travel/HN.yml
>    - "[The curfew remains in place](https://www.garda.com/crisis24/news-alerts/365846/honduras-nationwide-curfew-extended-until-august-9-update-14)
single `'`

2020-08-25 03:47 UTC, jannwong commented on public/data/travel/MZ.yml
> +  - "Mozambicans can now leave and enter the country without needing to gain authorization from the interior minister. [Foreigners can also leave and enter the country](https://www.garda.com/crisis24
single `'`

2020-08-25 03:48 UTC, jannwong requested changes
![](https://media2.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif)

2020-08-25 04:01 UTC, gabriel-seow commented on public/data/travel/HN.yml
>    - "[The curfew remains in place](https://www.garda.com/crisis24/news-alerts/365846/honduras-nationwide-curfew-extended-until-august-9-update-14)
hello jann! I clarified this with mirha already, all the '' that you see is the github system and mirha's script appearing that way. So whatever appears in that manner, I just left it because when I open the file it comes out as that already anyway!

2020-08-25 07:08 UTC, jannwong approved these changes
![](https://media1.giphy.com/media/RNWCNuJtSZjWTtJrTg/giphy.gif)

2020-08-25 07:09 UTC, merged