Update KR
tourhero/travel-reopening pull request #302
Opened 2020-08-24 09:24 UTC by jerometeo

2020-08-24 10:43 UTC, jannwong commented on public/data/travel/KR.yml
>    - The Ministry of Health and Welfare issued a statement on Sunday, June 21, announcing
Sunday is not relevant. We should also state June 21, 2020 so that we don't need to update next year

2020-08-24 10:44 UTC, jannwong commented on public/data/travel/KR.yml
>    - The Ministry of Health and Welfare issued a statement on Sunday, June 21, announcing
there's also missing ' in the beginning and end

2020-08-24 10:44 UTC, jannwong requested changes
![](https://media2.giphy.com/media/l4q8bXnHI4k7Wv9kY/giphy.gif)

2020-08-25 06:35 UTC, gabriel-seow commented on public/data/travel/KR.yml
>    - The Ministry of Health and Welfare issued a statement on Sunday, June 21, announcing
Hi Jann, (this is gab), so for github direct entries, the ' does not appear at the start and end in general, because it's just the way the system works, as well as a script thing according to what mirha explained to me, and it does not affect anything at all! So just an FYI

2020-08-25 06:38 UTC, gabriel-seow commented on public/data/travel/KR.yml
>    - The Ministry of Health and Welfare issued a statement on Sunday, June 21, announcing
Also, the june 21, 2020 thing is already updated!

2020-08-25 10:00 UTC, jannwong approved these changes
![](https://media3.giphy.com/media/5tamwFxY7PTW0/giphy.gif)

2020-08-25 10:00 UTC, merged