Update FI
tourhero/travel-reopening pull request #303
Opened 2020-08-24 09:52 UTC by sherryw94

2020-08-24 10:45 UTC, jannwong commented on public/data/travel/FI.yml
>    - "[Domestic travel allowed](https://valtioneuvosto.fi/en/article/-/asset_publisher/10616/muutoksia-koronavirusepidemian-vuoksi-asetettuihin-rajoituksiin-1-kesakuuta)
should be single `'` not `"`

2020-08-24 10:45 UTC, jannwong commented on public/data/travel/FI.yml
> +  - '[Events with more than 500 attendees will be permitted from August 31, 2020](https://valtioneuvosto.fi/en/information-on-coronavirus/current-restrictions), both indoors and outdoors, providing c
hyperlink can be shortened

2020-08-24 10:46 UTC, jannwong requested changes
![](https://media2.giphy.com/media/RJ198BpRrxSeD9Y06x/giphy.gif)

2020-08-25 06:20 UTC, sherryw94 commented on public/data/travel/FI.yml
>    - "[Domestic travel allowed](https://valtioneuvosto.fi/en/article/-/asset_publisher/10616/muutoksia-koronavirusepidemian-vuoksi-asetettuihin-rajoituksiin-1-kesakuuta)
gab's instructions to not change it because it is the original appearance when i open the file.

2020-08-25 07:48 UTC, jannwong approved these changes
![](https://media0.giphy.com/media/T9AfyOYnJACQ0/giphy.gif)

2020-08-25 07:49 UTC, merged