Add zoom controls
tourhero/travel-reopening pull request #310
Opened 2020-08-25 09:55 UTC by mirhamasala

- Create `ZoomControl` component
- Add zoom in and zoom out functionality to `WorldMap`

2020-08-25 09:59 UTC, mirhamasala commented
@yurikoval Only thing left is to position the zoom controls on the map. I'll do that tomorrow. Just creating a draft pull request in case you already want to review the code. ☀️

2020-08-25 12:10 UTC, yurikoval requested changes

2020-08-25 12:10 UTC, yurikoval commented on src/components/Map/WorldMap.vue
> +      const zoomer = zoom().scaleExtent([1, 50]).on('zoom', zoomHandler.bind(this));
Let's refactor the magic `[1, 50]` or maybe the zoomer itself out into a property or a constant.

2020-08-26 03:40 UTC, yurikoval approved these changes

2020-08-26 03:40 UTC, merged